### ISSUE TITLE
Is intercooler dead? No commits on this repo? Is there a new library that has overtaken, why did everyone ditch it?

### ISSUE THREAD

**Issue by codecraf8** [brejoc/django-intercoolerjs#15]

**Comment by brejoc** [comment]
You are probably looking at the wrong repo. This is just a Django wrapper around intercooler.js. For the intercooler Github repo look [here](https://github.com/intercoolerjs/intercooler-js).

I'm closing this issue. Feel free to re-open this issue if you think this should stay open.
