### ISSUE TITLE
Switch to Markdown for README

### ISSUE THREAD

**Issue by brejoc** [brejoc/django-intercoolerjs#3]
Problems with md made me use rst.

**Comment by brejoc** [comment]
Since pypi still only supports rst, we need this in the setup.py:

```Python
try:
    import pypandoc
    long_description = pypandoc.convert('README.md', 'rst')
except ImportError:
    long_description = open('README.md').read()
```

**Comment by blfpd** [comment]
Why would you need Markdown? Rst is fine for Python project :)

**Comment by brejoc** [comment]
Just a personal preference. :smile:

**Comment by pradyunsg** [comment]
I would be interested in taking this on.

**Comment by brejoc** [comment]
@pradyunsg Sure, go on! Just fork the repo, make your changes and open a pull request.

**Comment by pradyunsg** [comment]
I'll make a PR sometime next week? October isn't here yet. :3

**Comment by drevantonder** [comment]
So you want the .rst removed and changed to a .md.
